CREATE TABLE AIRLINE(
	CODE INT PRIMARY KEY,
	NAME CHAR(255) NOT NULL,
	COUNTRY CHAR(255),
    CONSTRAINT UC_AIRLINE UNIQUE(NAME, COUNTRY)
);

CREATE TABLE AGENCY(
	NAME CHAR(255) PRIMARY KEY,
	COUNTRY CHAR(255) NOT NULL,
	CITY CHAR(255) NOT NULL,
	PHONE INT NOT NULL
);

CREATE TABLE AIRPLANE(
	CODE INT PRIMARY KEY,
	TYPE CHAR(255) NOT NULL,
	SEATS INT CHECK (SEATS > 0),
	YEAR INT NOT NULL
);

CREATE TABLE AIRPORT(
	CODE INT PRIMARY KEY,
	NAME CHAR(255) NOT NULL,
	COUNTRY CHAR(255) NOT NULL,
	CITY CHAR(255)
    CONSTRAINT UC_AIRPORT UNIQUE(NAME, COUNTRY)
);

CREATE TABLE CUSTOMER(
	ID INT PRIMARY KEY,
	FNAME CHAR(255) NOT NULL,
	LNAME CHAR(255) NOT NULL,
	EMAIL CHAR(255) CHECK (EMAIL LIKE '%_@_%.__%')
);

CREATE TABLE FLIGHT(
	FNUMBER INT PRIMARY KEY,
	AIRLINE_OPERATOR INT,
	DEP_AIRPORT INT,
	ARR_AIRPORT INT,
	FLIGHT_TIME TIME,
	FLIGHT_DURATION TIME NOT NULL,
	AIRPLANE INT NOT NULL,
    FOREIGN KEY (AIRLINE_OPERATOR) REFERENCES AIRLINE(CODE),
    FOREIGN KEY (AIRPLANE) REFERENCES AIRPLANE(CODE),
    FOREIGN KEY (DEP_AIRPORT) REFERENCES AIRPORT(CODE),
    FOREIGN KEY (ARR_AIRPORT) REFERENCES AIRPORT(CODE)
);

CREATE TABLE BOOKING(
	CODE INT PRIMARY KEY,
	AGENCY CHAR(255),
    AIRLANE_CODE INT,
	FLIGHT_NUMBER INT,
	CUSTOMER_ID INT,
	BOOKING_DATE DATE ,
	FLIGHT_DATE DATE CHECK (FLIGHT_DATE >= BOOKING_DATE),
	PRICE INT,
	STATUS CHAR(1) CHECK (STATUS = '0' OR STATUS = '1'),
    FOREIGN KEY (AIRLANE_CODE) REFERENCES AIRLINE(CODE),
    FOREIGN KEY (AGENCY) REFERENCES AGENCY(NAME),
    FOREIGN KEY (FLIGHT_NUMBER) REFERENCES FLIGHT(FNUMBER),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID)
);

