--1--
SELECT AVG(SPEED) AS AvgSpeed
FROM PC;

--2--
SELECT maker, AVG(screen) AS AvgScreen
FROM laptop
JOIN product ON laptop.model = product.model
GROUP BY maker;

--3--
SELECT AVG(speed) AS AvgSpeed
FROM laptop
WHERE price > 1000;

--4--
SELECT MAKER, AVG(PRICE) AS AvgPrice
FROM pc
JOIN product ON pc.model = product.model
WHERE MAKER = 'A'
GROUP BY MAKER;

--5--
SELECT MAKER, AVG(PRICE_)
FROM 
(SELECT MAKER, PRICE AS PRICE_
FROM PRODUCT
JOIN LAPTOP ON PRODUCT.MODEL = LAPTOP.MODEL
WHERE MAKER = 'B'
UNION ALL
SELECT MAKER, PRICE AS PRICE_
FROM PRODUCT
JOIN PC ON PRODUCT.MODEL = PC.MODEL
WHERE MAKER = 'B') AS B_PRODUCT
GROUP BY MAKER;

--6--
SELECT SPEED, AVG(PRICE)
FROM PC
GROUP BY SPEED;

--7--
SELECT MAKER, number_of_pc
FROM 
(SELECT MAKER, COUNT(DISTINCT code) AS number_of_pc
FROM product
JOIN pc ON product.model = pc.model
GROUP BY MAKER) AS maker_pcs
WHERE number_of_pc >= 3;

--8--
SELECT TOP 1 MAKER, MAX(PRICE)
FROM PRODUCT
JOIN PC ON PRODUCT.model = PC.model
GROUP BY MAKER;

--9--
SELECT SPEED, AVG(PRICE) AS AvgPrice
FROM PC
WHERE SPEED > 800
GROUP BY SPEED;

--10--
SELECT MAKER, AVG(PC.HD) AS AvgHDD
FROM PRODUCT
JOIN PC ON PRODUCT.MODEL = PC.MODEL
WHERE MAKER IN 
(SELECT MAKER
FROM PRODUCT
WHERE TYPE = 'Printer')
GROUP BY MAKER;

