--1--
SELECT DISTINCT P.MAKER, P.MODEL, P.TYPE
FROM PRODUCT P
LEFT JOIN PC ON P.MODEL = PC.MODEL
LEFT JOIN LAPTOP L ON P.MODEL = L.MODEL
LEFT JOIN PRINTER PR ON P.MODEL = PR.MODEL
WHERE PC.MODEL IS NULL AND L.MODEL IS NULL AND PR.MODEL IS NULL;

--2--
SELECT MAKER
FROM PRODUCT P
LEFT JOIN PC ON P.model = PC.model
LEFT JOIN LAPTOP L ON P.model = L.model
LEFT JOIN PRINTER PR ON PR.model = PR.model
WHERE P.type = 'Laptop' AND P.type = 'Printer';

--3--
SELECT HD
FROM LAPTOP
GROUP BY HD
HAVING COUNT(*) >= 2;

--4--
SELECT P.MODEL
FROM PRODUCT P
LEFT JOIN PC ON P.MODEL = PC.MODEL
WHERE PC.MODEL IS NULL;
