--1--
SELECT NAME FROM SHIPS JOIN CLASSES ON SHIPS.CLASS = CLASSES.CLASS WHERE CLASSES.DISPLACEMENT > 50000;

--2--
SELECT SHIPS.NAME, CLASSES.DISPLACEMENT, CLASSES.NUMGUNS FROM SHIPS
JOIN CLASSES ON SHIPS.CLASS = CLASSES.CLASS JOIN OUTCOMES ON SHIPS.NAME = OUTCOMES.SHIP WHERE OUTCOMES.BATTLE = 'Guadalcanal';

--3--
SELECT DISTINCT COUNTRY FROM CLASSES WHERE TYPE = 'bc' AND COUNTRY IN (SELECT COUNTRY FROM CLASSES WHERE TYPE = 'bb');

--4--
SELECT S1.SHIP FROM OUTCOMES S1 WHERE S1.RESULT = 'damaged' AND S1.SHIP IN (SELECT S2.SHIP FROM OUTCOMES S2 WHERE S2.RESULT != 'damaged' AND S2.SHIP = S1.SHIP);