--1--
SELECT P.MAKER, L.SPEED FROM PRODUCT P JOIN LAPTOP L ON P.MODEL = L.MODEL WHERE L.HD >= 9;

--2--
SELECT DISTINCT P.MODEL, PC.PRICE AS PRICE, L.PRICE AS PRICE, PR.PRICE AS PRICE FROM PRODUCT P
LEFT JOIN PC ON P.MODEL = PC.MODEL LEFT JOIN LAPTOP L ON P.MODEL = L.MODEL
LEFT JOIN PRINTER PR ON P.MODEL = PR.MODEL WHERE P.MAKER = 'B';

--3--
SELECT MAKER FROM PRODUCT GROUP BY MAKER HAVING SUM(CASE WHEN type = 'Laptop' THEN 1 ELSE 0 END) > 0
AND SUM(CASE WHEN type = 'PC' THEN 1 ELSE 0 END) = 0

--4--
SELECT HD FROM PC GROUP BY HD HAVING COUNT(DISTINCT CODE) >= 2;

--5--
SELECT DISTINCT A.MODEL, B.MODEL FROM PC A, PC B WHERE A.SPEED = B.SPEED AND A.RAM = B.RAM AND A.MODEL < B.MODEL;

--6--
SELECT P.MAKER FROM PC JOIN PRODUCT P ON PC.MODEL = P.MODEL WHERE PC.SPEED >= 400 GROUP BY P.MAKER HAVING COUNT(DISTINCT PC.CODE) >= 2;