--1--
SELECT P.MAKER, L.SPEED 
FROM PRODUCT P 
JOIN LAPTOP L ON P.MODEL = L.MODEL 
WHERE L.HD >= 9;

--2--
SELECT P.MODEL, PC.PRICE AS PRICE
FROM PRODUCT P
LEFT JOIN PC ON P.MODEL = PC.MODEL 
WHERE P.MAKER = 'B'
UNION
SELECT P.MODEL, L.PRICE AS PRICE
FROM PRODUCT P
LEFT JOIN LAPTOP L ON P.MODEL = L.MODEL
WHERE P.MAKER = 'B'
UNION
SELECT P.MODEL, PR.PRICE AS PRICE
FROM PRODUCT P
LEFT JOIN PRINTER PR ON P.MODEL = PR.MODEL 
WHERE P.MAKER = 'B';

--3--
SELECT P.MAKER
FROM PRODUCT P
WHERE P.TYPE = 'Laptop' AND P.MAKER NOT IN 
(SELECT P2.MAKER
FROM PRODUCT P2
WHERE P2.TYPE = 'PC');

--4--
SELECT HD 
FROM PC 
GROUP BY HD 
HAVING COUNT(DISTINCT CODE) >= 2;

--5--
SELECT DISTINCT A.MODEL, B.MODEL 
FROM PC A, PC B 
WHERE A.SPEED = B.SPEED AND A.RAM = B.RAM AND A.MODEL < B.MODEL;

--6--
SELECT P.MAKER 
FROM PC JOIN PRODUCT P 
ON PC.MODEL = P.MODEL 
WHERE PC.SPEED >= 400 
GROUP BY P.MAKER 
HAVING COUNT(DISTINCT PC.CODE) >= 2;