--10--
UPDATE CLASSES
SET NUMGUNS += 9*2, BORE += 16*2, DISPLACEMENT += 34000*2
WHERE CLASS = 'Nelson'
INSERT INTO SHIPS
VALUES ('Nelson', 'Nelson', 1927);
INSERT INTO SHIPS
VALUES ('Rodney', 'Nelson', 1927);


--11--
DELETE FROM SHIPS
WHERE NAME IN 
(SELECT SHIP
FROM OUTCOMES
WHERE RESULT = 'sunk');

--12--
UPDATE CLASSES
SET BORE = BORE * 2.5, DISPLACEMENT = DISPLACEMENT * 1.1;
