--1--
SELECT MODEL, SPEED AS MHz, HD AS GB 
FROM PC 
WHERE PRICE < 1200;

--2--
SELECT DISTINCT MAKER 
FROM PRODUCT 
WHERE TYPE = 'Printer';

--3--
SELECT MODEL, RAM, SCREEN 
FROM LAPTOP 
WHERE PRICE > 1000;

--4--
SELECT * 
FROM PRINTER 
WHERE COLOR = 'y';

--5--
SELECT MODEL, HD AS MHz, CD AS GB 
FROM PC 
WHERE (CD = '12x' OR CD = '16x') AND PRICE < 2000;