--1--
SELECT ADDRESS FROM STUDIO WHERE NAME = 'Disney';

--2--
SELECT BIRTHDATE FROM MOVIESTAR WHERE NAME = 'Jack Nicholson';

--3--
SELECT S.NAME FROM MOVIESTAR S 
INNER JOIN STARSIN SI ON S.NAME = SI.STARNAME
INNER JOIN MOVIE M ON SI.MOVIETITLE = M.TITLE AND SI.MOVIEYEAR = M.YEAR
WHERE M.YEAR = 1980 OR M.TITLE LIKE '%Knight%';

--4--
SELECT NAME FROM MOVIEEXEC WHERE NETWORTH > 10000000;

--5--
SELECT NAME FROM MOVIESTAR WHERE GENDER = 'M' OR ADDRESS = 'Prefect Rd.';