--1--
SELECT MS.NAME 
FROM MOVIESTAR MS
JOIN STARSIN SI ON MS.NAME = SI.STARNAME 
JOIN MOVIE M ON SI.MOVIETITLE = M.TITLE AND SI.MOVIEYEAR = M.YEAR 
JOIN MOVIEEXEC ME ON M.PRODUCERC# = ME.CERT#
WHERE MS.GENDER = 'F' AND ME.NETWORTH > 10000000 AND MS.NAME = ME.NAME;

--2--
SELECT DISTINCT MS.NAME 
FROM MOVIESTAR MS 
WHERE NAME NOT IN 
(SELECT NAME FROM STARSIN SI
JOIN MOVIE M ON SI.MOVIETITLE = M.TITLE AND SI.MOVIEYEAR = M.YEAR 
JOIN MOVIEEXEC ME ON M.PRODUCERC# = ME.CERT#
WHERE MS.NAME != ME.NAME);

--3--
SELECT TITLE 
FROM MOVIE 
WHERE LENGTH > 
(SELECT LENGTH 
FROM MOVIE 
WHERE TITLE = 'Star Wars');

--4--
SELECT M.TITLE, ME.NAME 
FROM MOVIE M 
JOIN MOVIEEXEC ME ON M.PRODUCERC# = ME.CERT# 
WHERE ME.NETWORTH > 
(SELECT NETWORTH 
FROM MOVIEEXEC 
WHERE NAME = 'Merv Griffin'); 
