--1--
SELECT DISTINCT COUNTRY
FROM CLASSES
WHERE NUMGUNS =
(SELECT MAX(NUMGUNS )
FROM CLASSES);

--2--
SELECT DISTINCT CLASSES.CLASS
FROM CLASSES
JOIN SHIPS ON CLASSES.CLASS = SHIPS.CLASS
JOIN OUTCOMES ON SHIPS.NAME = OUTCOMES.SHIP
WHERE OUTCOMES.RESULT = 'sunk';

--3--
SELECT SHIPS.NAME, SHIPS.CLASS
FROM SHIPS
INNER JOIN CLASSES ON SHIPS.CLASS = CLASSES.CLASS
WHERE CLASSES.BORE = 16;

--4--
SELECT OUTCOMES.BATTLE
FROM OUTCOMES
JOIN SHIPS ON OUTCOMES.SHIP = SHIPS.NAME
WHERE SHIPS.CLASS =  'Kongo';

--5--
SELECT DISTINCT SHIPS.CLASS, NAME
FROM SHIPS
JOIN CLASSES CL1 ON SHIPS.CLASS = CL1.CLASS
WHERE CL1.NUMGUNS >= ALL
(SELECT CL2.NUMGUNS
FROM CLASSES CL2
WHERE CL1.NUMGUNS = CL2.NUMGUNS)
ORDER BY CLASS;