--1--
SELECT DISTINCT SHIPS.NAME
FROM SHIPS
RIGHT JOIN OUTCOMES ON SHIPS.NAME = OUTCOMES.SHIP
WHERE SHIPS.NAME LIKE 'C%' OR SHIPS.NAME LIKE 'K%';

--2--
SELECT SHIPS.NAME, CLASSES.COUNTRY
FROM SHIPS
JOIN CLASSES ON SHIPS.CLASS = CLASSES.CLASS
WHERE SHIPS.NAME NOT IN 
(SELECT OUTCOMES.SHIP
FROM OUTCOMES
WHERE OUTCOMES.RESULT = 'sunk');

--3--
SELECT CLASSES.COUNTRY, COUNT(OUTCOMES.SHIP) AS num_sunk_ships
FROM CLASSES 
LEFT JOIN SHIPS ON CLASSES.CLASS = SHIPS.CLASS
LEFT JOIN OUTCOMES ON SHIPS.NAME = OUTCOMES.SHIP
WHERE OUTCOMES.RESULT = 'sunk' OR OUTCOMES.RESULT IS NULL
GROUP BY CLASSES.COUNTRY;

--4--
SELECT BATTLES.NAME
FROM BATTLES
WHERE 
(SELECT COUNT(OUTCOMES.SHIP)
FROM OUTCOMES
WHERE OUTCOMES.BATTLE = BATTLES.NAME) > 
(SELECT COUNT(OUTCOMES.SHIP)
FROM OUTCOMES
WHERE OUTCOMES.BATTLE = 'Guadalcanal');

--5--
SELECT BATTLES.NAME 
FROM BATTLES
WHERE 
(SELECT COUNT(OUTCOMES.SHIP)
FROM OUTCOMES
WHERE OUTCOMES.BATTLE = BATTLES.NAME) > 
(SELECT COUNT(OUTCOMES.SHIP)
FROM OUTCOMES
WHERE OUTCOMES.BATTLE = 'Surigao Strait');


--6--
SELECT SHIPS.NAME, MIN(CLASSES.DISPLACEMENT) AS displacement, MAX(CLASSES.NUMGUNS) AS numGuns
FROM SHIPS
JOIN CLASSES ON SHIPS.CLASS = CLASSES.CLASS
GROUP BY SHIPS.NAME
ORDER BY CLASSES.DISPLACEMENT ASC;

--7--
SELECT DISTINCT COUNT(S1.NAME) AS NUM_SHIPS
FROM SHIPS AS S1
JOIN OUTCOMES AS O1 ON S1.NAME = O1.SHIP AND O1.RESULT = 'damaged'
JOIN BATTLES AS B1 ON O1.BATTLE = B1.NAME
JOIN SHIPS AS S2 ON S1.NAME = S2.NAME
JOIN OUTCOMES AS O2 ON S2.NAME = O2.SHIP AND O2.RESULT = 'ok'
JOIN BATTLES AS B2 ON O2.BATTLE = B2.NAME
WHERE B2.DATE > B1.DATE

--8--
SELECT DISTINCT S1.NAME
FROM SHIPS AS S1
JOIN OUTCOMES AS O1 ON S1.NAME = O1.SHIP AND O1.RESULT = 'damaged'
JOIN BATTLES AS B1 ON O1.BATTLE = B1.NAME
JOIN SHIPS AS S2 ON S1.NAME = S2.NAME
JOIN OUTCOMES AS O2 ON S2.NAME = O2.SHIP AND O2.RESULT = 'ok'
JOIN BATTLES AS B2 ON O2.BATTLE = B2.NAME
WHERE B2.DATE > B1.DATE