--1--
SELECT MODEL, CODE, SCREEN
FROM LAPTOP
WHERE SCREEN = 15 OR SCREEN = 11;

--2--
SELECT DISTINCT P1.MODEL
FROM PRODUCT P1
JOIN PC ON P1.model = PC.model
WHERE PC.PRICE <
(SELECT MIN(LAPTOP.PRICE)
FROM PRODUCT P2 
JOIN LAPTOP ON P2.MODEL = LAPTOP.MODEL AND P1.MAKER = P2.MAKER);

--3--
SELECT P1.MODEL, AVG(PRICE) AS avg_price
FROM PRODUCT P1
JOIN PC ON P1.model = PC.model
WHERE P1.type = 'PC' AND 
(SELECT AVG(PRICE)
FROM PC
WHERE P1.MODEL = PC.MODEL) <
(SELECT MIN(PRICE)
FROM PRODUCT P2
JOIN LAPTOP ON P2.model = LAPTOP.model
WHERE P2.type = 'Laptop' AND P1.maker = P2.maker)
GROUP BY P1.MODEL;

--4--
SELECT CODE, MAKER, COUNT(PRICE) AS NUM_PC_HIGHER_PRICE
FROM PC
LEFT JOIN PRODUCT ON PC.model = PRODUCT.model
WHERE PC.PRICE >= PRICE
GROUP BY CODE, PRODUCT.MAKER;
