--1--
SELECT MOVIE.TITLE, MOVIE.YEAR, MOVIE.LENGTH
FROM MOVIE
WHERE (MOVIE.LENGTH > 120 OR MOVIE.LENGTH IS NULL) AND MOVIE.YEAR < 2000;

--2--
SELECT MOVIESTAR.NAME, GENDER 
FROM MOVIESTAR
WHERE NAME LIKE 'J%' AND BIRTHDATE > 1948
ORDER BY NAME DESC;

--3--
SELECT MOVIE.STUDIONAME, COUNT(STARSIN.STARNAME) AS num_movies
FROM MOVIE
JOIN STARSIN ON MOVIE.TITLE = STARSIN.MOVIETITLE
GROUP BY MOVIE.STUDIONAME;

--4--
SELECT STARSIN.STARNAME, COUNT(STARSIN.MOVIETITLE) AS num_movies
FROM STARSIN
GROUP BY STARSIN.STARNAME;

--5--
SELECT STUDIO.NAME AS StudioName, MOVIE.TITLE, MOVIE.YEAR
FROM STUDIO
INNER JOIN MOVIE ON STUDIO.NAME = MOVIE.STUDIONAME
WHERE MOVIE.YEAR = (SELECT MAX(MOVIE.YEAR) FROM MOVIE WHERE MOVIE.STUDIONAME = STUDIO.NAME);

--6--
SELECT MOVIESTAR.NAME
FROM MOVIESTAR
WHERE MOVIESTAR.BIRTHDATE = (
  SELECT MAX(MOVIESTAR.BIRTHDATE)
  FROM MOVIESTAR
  WHERE MOVIESTAR.GENDER = 'M'
)
ORDER BY NAME;

--7--
WITH ActorMovieCount AS (
  SELECT
    STARSIN.STARNAME,
    MOVIE.STUDIONAME,
    COUNT(*) AS MovieCount
  FROM
    STARSIN
    INNER JOIN MOVIE ON STARSIN.MOVIETITLE = MOVIE.TITLE AND STARSIN.MOVIEYEAR = MOVIE.YEAR
  GROUP BY
    STARSIN.STARNAME, MOVIE.STUDIONAME
),
StudioMaxMovies AS (
  SELECT
    STUDIONAME,
    MAX(MovieCount) AS MaxMovies
  FROM
    ActorMovieCount
  GROUP BY
    STUDIONAME
)
SELECT
  ActorMovieCount.STARNAME AS ActorName,
  ActorMovieCount.STUDIONAME AS StudioName,
  ActorMovieCount.MovieCount AS NumMovies
FROM
  ActorMovieCount
  INNER JOIN StudioMaxMovies ON ActorMovieCount.STUDIONAME = StudioMaxMovies.STUDIONAME AND ActorMovieCount.MovieCount = StudioMaxMovies.MaxMovies;


--8--
SELECT MOVIE.TITLE, MOVIE.YEAR, COUNT(STARSIN.STARNAME) AS num_actors
FROM MOVIE
JOIN STARSIN ON MOVIE.TITLE = STARSIN.MOVIETITLE AND MOVIE.YEAR = STARSIN.MOVIEYEAR
GROUP BY MOVIE.TITLE, MOVIE.YEAR
HAVING COUNT(STARSIN.STARNAME) > 2;
